# Generated by Django 4.2.1 on 2023-07-18 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="crypto_amount",
        ),
    ]
