version: '3.2'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    tty: true
    volumes:
      - static_volume:/app/src/core/static
      - media_volume:/app/src/core/media
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - static_volume:/app/src/core/static  # <-- bind the static volume
      - media_volume:/app/src/core/media  # <-- bind the media volume
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume: