version: '3.2'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgresql
    hostname: postgresql
    environment:
      POSTGRES_DB: crypto_db
      POSTGRES_USER: javadfarah
      POSTGRES_PASSWORD: javadfarah
      POSTGRES_ROOT_PASSWORD: root
      PGDATA: /var/lib/postgresql/mydb
    ports:
      - '5432:5432'
    expose:
      - '5432'
    networks:
      - nginx_network
    volumes:
      - ./postgres:/var/lib/postgresql/mydb
  web:
    build:
      dockerfile: Dockerfile
      context: .
    tty: true
    environment:
      - DJANGO_SUPERUSER_PASSWORD=123
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=m.farahnak1996@gmail.com
    volumes:
      - static_volume:/app/src/core/static
      - media_volume:/app/src/core/media
    networks:
      - nginx_network
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - static_volume:/app/src/core/static  # <-- bind the static volume
      - media_volume:/app/src/core/media  # <-- bind the media volume
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres:
    external: true
  metabase: