# Generated by Django 4.2.1 on 2023-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("crypto_name", models.CharField(max_length=255)),
                ("crypto_amount", models.PositiveIntegerField()),
                ("orders", models.ManyToManyField(to="user.order")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
