# Generated by Django 4.2.1 on 2023-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderqueue",
            old_name="crypto_amount",
            new_name="total_amount",
        ),
    ]
